### PR TITLE
Fix julia 0.4 warnings

### PR DESCRIPTION
**Pull request by davidanthoff**
This fixes depreciation warnings on the julia 0.4 release candiate. Would be great if a new release at 0.4.x could be tagged with these patches. 

I didn't make this julia 0.3 compatible, given that the 0.4.x Lora series is julia 0.4 only anyways.

### CODE REVIEW

**Comment by scidom** [comment]
Ok, I will merge this although it is going to render itself irrelevant in 4 to 6 weeks on the basis of the forthcoming development cycle. Lora's autodiff capabilities will be entirely based on the excellent ReverseDiffSource package of @fredo-dedup, but soon will have to temporarily disable this autodiff feature until I code an extra layer that will be sitting on top of the ongoing developed infrastructure of the 0.5.0 dev branch. Once this layer of glue code is completed in Lora, it will be reconnected with ReverseDiffSource to re-enable autodiff. This may cause a bit of inconvenience in about 2 months from now as far as autodiff goes, but it is needed to temporarily take these steps so that the long-standing developed code lands. Then extra features will get added (or re-added). I will merge for now, and will submit a metadata PR by tomorrow.

**Comment by scidom** [comment]
P.S. I closed it at the beginning by mistake instead of merging, but fixed it, it's been merged now.

**Comment by davidanthoff** [comment]
Sure, just trying to have a code-base that works now on julia 0.4 until the new stuff lands.

**Comment by scidom** [comment]
Yes, it's good you did this :+1:

**Comment by davidanthoff** [comment]
Oh, one more thing: can you hold of tagging for a bit? I have one more PR coming for the 0.4.x line, small thing but useful.

**Comment by scidom** [comment]
That's all right, I just moved in a new city and flat with public wireless internet for now, so will hold off with metadata PRs till tomorrow so as to do it from a stable office internet connection.

**Comment by davidanthoff** [comment]
Sounds good.

**Pull request merged**
